[visualization]
export = true
export_interval = 10

   [[visualize_sim_object]]
   name = "MyCell"
   additional_data_members = [ "diameter_", "cell_color_"]


#   [[visualize_diffusion]]
#   name = "Substance"
#   gradient = true
